import React from 'react';
import { PhoneCall, MessageSquareMore, CalendarX, Repeat, FileText, BarChart3 } from 'lucide-react';

const features = [
  {
    icon: PhoneCall,
    title: "AI Voice Concierge",
    description: "Our high-fidelity voice AI answers calls with your brand's specific tone, handling FAQs and booking appointments directly.",
    color: "bg-blue-600",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400"
  },
  {
    icon: MessageSquareMore,
    title: "Instant Lead Capture",
    description: "Every missed call or web inquiry is met with a personalized SMS sequence within 30 seconds of the event.",
    color: "bg-emerald-600",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=400"
  },
  {
    icon: CalendarX,
    title: "The No-Show Shield",
    description: "Automated deposit collection and multi-channel reminders reduce no-shows to industry-leading lows.",
    color: "bg-purple-600",
    image: "https://images.unsplash.com/photo-1445510861639-5651173bc5d5?auto=format&fit=crop&q=80&w=400"
  },
  {
    icon: Repeat,
    title: "Retention Engine",
    description: "Automatically reactivate dormant clients with personalized special offers based on their treatment history.",
    color: "bg-orange-600",
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=400"
  },
  {
    icon: FileText,
    title: "Digital Concierge",
    description: "Send and receive HIPAA-compliant intake forms and consent waivers via SMS before they even arrive.",
    color: "bg-pink-600",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=400"
  },
  {
    icon: BarChart3,
    title: "Precision Analytics",
    description: "Visual dashboards detailing every dollar recovered, lead converted, and ROI generated by the engine.",
    color: "bg-slate-600",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=400"
  }
];

const Features: React.FC = () => {
  return (
    <section id="features" className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-20">
          <h2 className="text-primary-600 font-bold tracking-[0.2em] uppercase text-sm mb-4">Elite Capabilities</h2>
          <h3 className="text-4xl md:text-5xl font-black text-slate-900 mb-6 tracking-tight">
            Engineered for Precision
          </h3>
          <p className="text-xl text-slate-500 font-medium">
            We don't just automate; we optimize every touchpoint of your patient's lifecycle.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {features.map((feature, index) => (
            <div key={index} className="group relative bg-slate-50 rounded-3xl overflow-hidden border border-slate-100 hover:shadow-2xl hover:shadow-slate-200 transition-all duration-500">
              <div className="h-48 overflow-hidden">
                <img 
                  src={feature.image} 
                  alt={feature.title} 
                  className="w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 group-hover:scale-110 transition-all duration-700"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-50 via-slate-50/20 to-transparent"></div>
              </div>
              
              <div className="p-8 relative -mt-12 bg-slate-50 rounded-t-3xl">
                <div className={`w-14 h-14 rounded-2xl ${feature.color} flex items-center justify-center mb-6 shadow-lg transform -rotate-3 group-hover:rotate-0 transition-transform`}>
                  <feature.icon className="h-7 w-7 text-white" />
                </div>
                <h4 className="text-2xl font-bold text-slate-900 mb-4 tracking-tight">{feature.title}</h4>
                <p className="text-slate-600 leading-relaxed font-medium">
                  {feature.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;